image: Visual Studio 2019
configuration: Release

# build config
build_script:
  - dotnet build .\src

# tests config
test_script:
  - dotnet test .\src

# pack config
after_test:
  - dotnet pack .\src

# artifacts config
artifacts:
  - path: '.\build\artifacts\*.nupkg'

# publish artifacts config
deploy:
  - provider: NuGet
    on:
      branch: master
    api_key:
      secure: Ursv3xUC5uIU3gNlDSgqpoF1pPfBYUTKFvz80rcSQZNF7s8VIoJ8xCiY7KQHiMja
